<?php

namespace App\Banque;

class CompteCourant extends \App\Banque\Compte
{
    /**
     * @var int
     */
    private int $decouvert;

    /**
     * @param string $nom
     * @param float $montant
     * @param int $decouvert
     */
    public function __construct(string $nom, float $montant, int $decouvert)
    {
        parent::__construct($nom, $montant);
        $this->decouvert = $decouvert;
    }

    /**
     * @return int
     */
    public function getDecouvert(): int
    {
        return $this->decouvert;
    }

    /**
     * @param $montant
     * @return $this
     */
    public function setDecouvert($montant): self
    {
        if ($montant >= 0) {
            $this->decouvert = $montant;
        }
        return $this;
    }

    public function retirer(float $montant): void
    {
        if ($montant > 0 && $this->solde - $montant >= -$this->decouvert) {
            $this->solde -= $montant;
        } else {
            echo "Solde insuffisant";
        }
        //parent::retirer($montant); // TODO: Change the autogenerated stub
    }
}